void saveobj(char* filename,int vertsperpoly,int vertexcount,float *vertexarray,float *texturearray){
	//open the file
	ofstream outdata;
	outdata.open(filename);
	//header
	outdata << "# Wavefront OBJ generated by ThatOtherPerson" << "\n" << "\n";
	//verts
	outdata << "# List of Vertices, with (x,y,z) coordinates" << "\n";
	for(int a=0;a<vertexcount;a++){
		outdata << "v";
		outdata << " " << vertexarray[a*3+0];
		outdata << " " << vertexarray[a*3+1];
		outdata << " " << vertexarray[a*3+2];
		outdata << "\n";
	}
	outdata << "# " << vertexcount << " vertices" << "\n" << "\n";
	//texture
	outdata << "# Texture coordinates, in (u,v) coordinates" << "\n";
	for(int a=0;a<vertexcount;a++){
		outdata << "vt";
		outdata << " " << texturearray[a*2+0];
		outdata << " " << texturearray[a*2+1];
		outdata << "\n";
	}
	outdata << "# " << vertexcount << " texture coordinates" << "\n" << "\n";
	//faces
	outdata << "# Face Definitions" << "\n";
	for(int a=0;a<vertexcount/vertsperpoly;a++){
		outdata << "f";
		for(int b=0;b<vertsperpoly;b++){
			outdata << " " << a*vertsperpoly+b+1;
			outdata << "/" << a*vertsperpoly+b+1;
		}
		outdata << "\n";
	}
	outdata << "# " << vertexcount/vertsperpoly << " polygons" << "\n" << "\n";
	//done
	outdata.close();
}
